name = "threat-intel-ingest"
main = "src/cloudflare/worker-threat-intel-ingest.js"
account_id = "e1b28dfdcf5e79b14ae5ac2eb01cb89d"
workers_dev = true
compatibility_date = "2023-08-01"


#[triggers] #triggers are temporarily disabled
#crons = ["*/15 * * * *"]


[vars]
MISP_API_KEY = "R2uokB95AfDSczhx0qmcAeTRRJ8CVv0CbbJIGMhs"
CF_ACCESS_CLIENT_ID = "8ba784aa2ffe6ef9216d21b937044e21.access"
CF_ACCESS_SERVICE_TOKEN = "ef37a74a6c4746b8c4b94e2c9ea4effcad982ed35ea6d8f856c78847f80e27dc"
NVD_API_KEY = "1574299d-9740-4785-8099-53d6268714ff"
RSS_API_KEY = ""
RSS_API_SECRET = ""
#FAUNA_SECRET = "fnAFWKEb-5AAUSnf98WwQAncoM9JxXYsa_JBEULp"


[[queues.producers]]
queue = "threat-intel-log-queue"
binding = "MY_QUEUE"
batch_size = 100 
max_batch_size = 1000
max_batch_timeout = 30
max_retries = 5


[[d1_databases]]
binding = "THREAT_INTEL_DB"
database_name = "threat_intel"
database_id = "a0f94c18-3778-43c6-899d-7390bb5f9d0d"

[[routes]]
pattern = "psight.network"
custom_domain = true

[[mtls_certificates]]
binding = "MY_CERT"
certificate_id = "04f4cbb2-6b28-419b-84dc-3c1927f28668"

[build]
command = "npm run build"

[observability]
enabled = true

name = "threat-intel-ingest-worker"
main = "worker-threat-intel-ingest.js"
compatibility_date = "2023-10-24"

[env.production]
routes = [
  "psight.network/fetchmisp",
  "psight.network/fetchnvd",
  "psight.network/fetchrss",
]
